### ISSUE TITLE
Make dynu updates more efficient

### ISSUE THREAD

**Issue by tronikos** [koying/ha-addons#25]
I see you first fetch https://ipv4.text.wtfismyip.com to get the IP address and then you call the v2 API.
This is unnecessary. Instead you could just use https://www.dynu.com/DynamicDNS/IP-Update-Protocol

Because you don't provide pre-built containers, see #24, I removed your addon and setup the let's encrypt addon for the certificate and the following rest sensor:

```yaml
rest:
  # https://www.dynu.com/DynamicDNS/IP-Update-Protocol
  - resource: https://api.dynu.com/nic/update?hostname=mydomain.freeddns.org&password=sha516ofmypassword
    scan_interval: 600
    sensor:
      - name: "Dynu nic update response"
        value_template: "{{ value }}"
```
